### ISSUE TITLE
Add example command lines to the documentation

### ISSUE THREAD

**Issue by Knitschi** [emosenkis/svndumpmultitool#2]
Hi,
it would be helpful if you added some examples of working commandlines to the documentation. I am not sure how to point the tool to the input and output dump files for example.

Thanks :)

**Comment by emosenkis** [comment]
I haven't touched this in over 6 years but here's a snippet from the scripts I used to use (basically, the input dump file is passed as `stdin` and the output is printed on `stdout`):

```shell
svnadmin dump <repo-path> -r <first>:<last> --incremental \
  | svndumpmultitool --repo=<repo-path> --include=<path-in-repo-to-include> \
  > out.svndump
```
